version: "3.8"
services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=csv-files
      - OLLAMA_API_URL=http://ollama:5000/api  # Adjust as necessary
    depends_on:
      - minio
      - ollama

  frontend:
    build: ./frontend
    container_name: vite-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data
    ports:
      - "9000:9000"

  ollama:
    image: your-ollama-image   # Replace with your actual Ollama container image
    container_name: ollama
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  minio-data:
